version: 2.1

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  build:
    working_directory: ~/articles
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: hello
          command: echo hello

  deploy:
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - run:
          name: world
          command: echo world
